# Generated by Django 2.0.7 on 2018-07-27 11:45

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='phone_no',
            field=models.BigIntegerField(blank=True, default=None, null=True, validators=[api.validators.validate_phoneno]),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='rating',
            field=models.IntegerField(choices=[(-1, -1), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=-1),
        ),
    ]
