# Generated by Django 2.0.3 on 2018-09-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180727_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
